### ISSUE TITLE
Editing a queued post with quick edit switches the post to a scheduled post

### ISSUE THREAD

**Issue by emdashcodes** [Automattic/post-queue#1]
Editing a queued post with quick edit switches the post to a `scheduled` post:

### Steps to reproduce:

1. Create a new post and set it to `queued`.
2. Save the post.
3. From the posts list (queued page), edit the post with quick edit.
4. Save the post.

### Expected behavior:

The post should remain queued.

### Actual behavior:

The post is switched to `scheduled`.

In addition, the UI becomes screwed up, perhaps thanks to the addition of our extra column.

**Comment by tommusrhodus** [comment]
@justinshreve Seems like https://github.com/Automattic/Edit-Flow/ may have worked on this issue (and likely others this may face)

**Comment by emdashcodes** [comment]
Fixed by https://github.com/Automattic/wp-post-queue/pull/19
